using System;
using System.Windows;

namespace K2.Core.Services;

/// <summary>
/// In-memory, app-wide clipboard for a single key's action (ActionType/ActionValue) — lets
/// the user copy/cut an action from any key on any device and paste it onto any other key on
/// any device (cross-device: DisplayPad, MacroPad, Everest Max incl. its numpad display keys,
/// Everest 60). Deliberately does NOT carry the source key's picture: the icon is a per-tile
/// rendering choice (size, crop, style), not part of "the action" — a target display key
/// (DisplayPad tile / Everest numpad display key) with no picture of its own gets a fresh
/// <see cref="ActionIconFallback"/> default instead, generated by each device's own
/// *PasteAction method at paste time.
/// Static/process-wide by design: K2.App hosts every device module in one process, so this is
/// effectively "the app's clipboard", not per-window state — pasting a DisplayPad key's action
/// onto an Everest Max key (or vice versa) is the point.
/// </summary>
public static class ActionClipboard
{
    public static string? ActionType  { get; private set; }
    public static string? ActionValue { get; private set; }

    /// <summary>False for an empty clipboard OR a stored "none"/empty type — mirrors every
    /// device key's own <c>HasAction</c> so "nothing to paste" and "action removed" agree.</summary>
    public static bool HasContent => !string.IsNullOrEmpty(ActionType) && ActionType != "none";

    public static void Copy(string? actionType, string? actionValue)
    {
        ActionType  = string.IsNullOrEmpty(actionType) || actionType == "none" ? null : actionType;
        ActionValue = ActionType is null ? null : actionValue;
    }

    /// <summary>
    /// True when the clipboard's action can be pasted onto a key belonging to
    /// <paramref name="host"/> — false only for a DisplayPad-page action
    /// (<see cref="ActionTypeHelper.PageOnlyActionTypes"/>) pasted onto a host with no page
    /// concept (MacroPad, Everest Max/60, the Everest numpad display keys — all
    /// <c>IActionHost.SupportsPages == false</c>). Callers show
    /// <see cref="ShowPasteUnsupportedError"/> when this returns false.
    /// </summary>
    public static bool CanPasteOn(IActionHost? host)
    {
        if (!HasContent) return false;
        if (host?.SupportsPages == true) return true;
        return Array.IndexOf(ActionTypeHelper.PageOnlyActionTypes, ActionType) < 0;
    }

    /// <summary>Shared error popup for a paste rejected by <see cref="CanPasteOn"/> — same
    /// wording/style everywhere it can happen (DisplayPad, MacroPad, Everest Max/60, numpad
    /// display keys).</summary>
    public static void ShowPasteUnsupportedError(Window? owner) =>
        MessageBox.Show(owner!, Loc.Get("paste_unsupported_message"), Loc.Get("paste_unsupported_title"),
            MessageBoxButton.OK, MessageBoxImage.Warning);
}
